=== IPK-BIT/isa-wizard/src/lib/schemas/investigation_schema.json
{
	"id": "https://raw.githubusercontent.com/ISA-tools/isa-api/master/isatools/resources/schemas/isa_model_version_1_0_schemas/core/investigation_schema.json",
	"$schema": "http://json-schema.org/draft-07/schema",
	"title": "ISA investigation schema",
	"description": "JSON-schema representing an investigation in the ISA model",
	"type": "object",
	"properties": {
		"@id": { "type": "string", "format": "uri" },
		"filename": { "type": "string" },
		"identifier": { "type": "string" },
		"title": { "type": "string" },
		"description": { "type": "string" },
		"submissionDate": { "type": "string", "format": "date-time" },
		"publicReleaseDate": { "type": "string", "format": "date-time" },
		"ontologySourceReferences": {
			"type": "array",
			"items": {
				"$ref": "ontology_source_reference_schema.json#"
			}
		},
		"publications": {
			"type": "array",
			"items": {
				"$ref": "publication_schema.json#"
			}
		},
		"people": {
			"type": "array",
			"items": {
				"$ref": "person_schema.json#"
			}
		},
		"studies": {
			"type": "array",
			"items": {
				"$ref": "study_schema.json#"
			}
		},
		"comments": {
			"type": "array",
			"items": {
				"$ref": "comment_schema.json#"
			}
		}
	},
	"additionalProperties": false
}

=== IPK-BIT/isa-wizard/test.json
{
    "@id": "",
    "filename": "",
    "identifier": "",
    "title": "",
    "description": "",
    "submissionDate": "",
    "publicReleaseDate": "",
    "ontologySourceReferences": [],
    "publications": [],
    "people": [],
    "studies": [
      {
        "@id": "",
        "filename": "studies/test/isa.study.xlsx",
        "identifier": "",
        "title": "test",
        "description": "",
        "submissionDate": "",
        "publicReleaseDate": "",
        "publications": [],
        "people": [],
        "studyDesignDescriptors": [],
        "protocols": [
          {
            "@id": "",
            "name": "Breedfides Growth",
            "description": "",
            "uri": "",
            "version": "",
            "parameters": [
              {
                "@id": "",
                "comments": [],
                "parameterName": {
                  "@id": "",
                  "annotationValue": "Year",
                  "termSource": "",
                  "termAccession": "",
                  "comments": []
                }
              },
              {
                "@id": "",
                "comments": [],
                "parameterName": {
                  "@id": "",
                  "annotationValue": "Location",
                  "termSource": "",
                  "termAccession": "",
                  "comments": []
                }
              },
              {
                "@id": "",
                "comments": [],
                "parameterName": {
                  "@id": "",
                  "annotationValue": "Repetition",
                  "termSource": "",
                  "termAccession": "",
                  "comments": []
                }
              },
              {
                "@id": "",
                "comments": [],
                "parameterName": {
                  "@id": "",
                  "annotationValue": "Block",
                  "termSource": "",
                  "termAccession": "",
                  "comments": []
                }
              }
            ],
            "components": [],
            "comments": []
          }
        ],
        "materials": {
          "sources": [
            {
              "@id": "",
              "characteristics": [
                {
                  "Organism": "Triticum aestivum",
                  "Genus": "Triticum",
                  "Species": "aestivum",
                  "Biological_material_latitude": "48.1333333333333",
                  "Biological_material_longitude": "1.13333333333333",
                  "Variety_name": "Actros"
                }
              ]
            },
            {
              "@id": "",
              "characteristics": [
                {
                  "Organism": "Triticum aestivum",
                  "Genus": "Triticum",
                  "Species": "aestivum",
                  "Biological_material_latitude": "50.5",
                  "Biological_material_longitude": "3.83333333333333",
                  "Variety_name": "Actros"
                }
              ]
            },
            {
              "@id": "",
              "characteristics": [
                {
                  "Organism": "Triticum aestivum",
                  "Genus": "Triticum",
                  "Species": "aestivum",
                  "Biological_material_latitude": "50",
                  "Biological_material_longitude": "8.15",
                  "Variety_name": "Actros"
                }
              ]
            },
            {
              "@id": "",
              "characteristics": [
                {
                  "Organism": "Triticum aestivum",
                  "Genus": "Triticum",
                  "Species": "aestivum",
                  "Biological_material_latitude": "50",
                  "Biological_material_longitude": "8.15",
                  "Variety_name": "Actros"
                }
              ]
            },
            {
              "@id": "",
              "characteristics": [
                {
                  "Organism": "Triticum aestivum",
                  "Genus": "Triticum",
                  "Species": "aestivum",
                  "Biological_material_latitude": "50",
                  "Biological_material_longitude": "8.15",
                  "Variety_name": "Actros"
                }
              ]
            },
            {
              "@id": "",
              "characteristics": [
                {
                  "Organism": "Triticum aestivum",
                  "Genus": "Triticum",
                  "Species": "aestivum",
                  "Biological_material_latitude": "48.3333333333333",
                  "Biological_material_longitude": "1.13333333333333",
                  "Variety_name": "Actros"
                }
              ]
            },
            {
              "@id": "",
              "characteristics": [
                {
                  "Organism": "Triticum aestivum",
                  "Genus": "Triticum",
                  "Species": "aestivum",
                  "Biological_material_latitude": "48.3333333333333",
                  "Biological_material_longitude": "1.13333333333333",
                  "Variety_name": "Actros"
                }
              ]
            },
            {
              "@id": "",
              "characteristics": [
                {
                  "Organism": "Triticum aestivum",
                  "Genus": "Triticum",
                  "Species": "aestivum",
                  "Biological_material_latitude": "50",
                  "Biological_material_longitude": "8.15",
                  "Variety_name": "Actros"
                }
              ]
            },
            {
              "@id": "",
              "characteristics": [
                {
                  "Organism": "Triticum aestivum",
                  "Genus": "Triticum",
                  "Species": "aestivum",
                  "Biological_material_latitude": "54.6666666666667",
                  "Biological_material_longitude": "9.03333333333333",
                  "Variety_name": "Actros"
                }
              ]
            }
          ],
          "samples": [
            {
              "@id": "",
              "characteristics": [],
              "factorValues": [],
              "derivesFrom": []
            },
            {
              "@id": "",
              "characteristics": [],
              "factorValues": [],
              "derivesFrom": []
            },
            {
              "@id": "",
              "characteristics": [],
              "factorValues": [],
              "derivesFrom": []
            },
            {
              "@id": "",
              "characteristics": [],
              "factorValues": [],
              "derivesFrom": []
            },
            {
              "@id": "",
              "characteristics": [],
              "factorValues": [],
              "derivesFrom": []
            },
            {
              "@id": "",
              "characteristics": [],
              "factorValues": [],
              "derivesFrom": []
            },
            {
              "@id": "",
              "characteristics": [],
              "factorValues": [],
              "derivesFrom": []
            },
            {
              "@id": "",
              "characteristics": [],
              "factorValues": [],
              "derivesFrom": []
            },
            {
              "@id": "",
              "characteristics": [],
              "factorValues": [],
              "derivesFrom": []
            }
          ],
          "otherMaterials": []
        },
        "processSequence": [
          {
            "@id": "",
            "name": "",
            "executesProtocol": {
              "@id": "",
              "name": "Breedfides Growth",
              "description": "",
              "uri": "",
              "version": "",
              "parameters": [
                {
                  "@id": "",
                  "comments": [],
                  "parameterName": {
                    "@id": "",
                    "annotationValue": "Year",
                    "termSource": "",
                    "termAccession": "",
                    "comments": []
                  }
                },
                {
                  "@id": "",
                  "comments": [],
                  "parameterName": {
                    "@id": "",
                    "annotationValue": "Location",
                    "termSource": "",
                    "termAccession": "",
                    "comments": []
                  }
                },
                {
                  "@id": "",
                  "comments": [],
                  "parameterName": {
                    "@id": "",
                    "annotationValue": "Repetition",
                    "termSource": "",
                    "termAccession": "",
                    "comments": []
                  }
                },
                {
                  "@id": "",
                  "comments": [],
                  "parameterName": {
                    "@id": "",
                    "annotationValue": "Block",
                    "termSource": "",
                    "termAccession": "",
                    "comments": []
                  }
                }
              ],
              "components": [],
              "comments": []
            },
            "parameterValues": [
              {
                "category": {
                  "@id": "",
                  "comments": [],
                  "parameterName": {
                    "@id": "",
                    "annotationValue": "Year",
                    "termSource": "",
                    "termAccession": "",
                    "comments": []
                  }
                },
                "value": "2009",
                "unit": {
