=== IPK-BIT/isa-wizard/src/lib/schemas/protocol_schema.json
{
	"id": "https://raw.githubusercontent.com/ISA-tools/isa-api/master/isatools/resources/schemas/isa_model_version_1_0_schemas/core/protocol_schema.json",
	"$schema": "http://json-schema.org/draft-07/schema",
	"title": "ISA protocol schema",
	"name": "ISA protocol schema",
	"description": "JSON-schema representing a protocol in the ISA model",
	"type": "object",
	"properties": {
		"@id": { "type": "string", "format": "uri" },
		"name": {
			"type": "string"
		},
		"protocolType": {
			"$ref": "ontology_annotation_schema.json#"
		},
		"description": {
			"type": "string"
		},
		"uri": {
			"type": "string",
			"format": "uri"
		},
		"version": {
			"type": "string"
		},
		"parameters": {
			"type": "array",
			"items": {
				"$ref": "protocol_parameter_schema.json#"
			}
		},
		"components": {
			"type": "array",
			"items": {
				"ref": "protocol_component_schema.json#"
			}
		},
		"comments": {
			"type": "array",
			"items": {
				"$ref": "comment_schema.json#"
			}
		}
	},
	"additionalProperties": false
}

=== IPK-BIT/isa-wizard/data/templates/protocols/breedfides.json
{
    "@id": "",
    "name": "Breedfides",
    "description": "",
    "uri": "",
    "version": "",
    "parameters": [
        {
            "@id": "",
            "comments": [],
            "parameterName": {
                "@id": "",
                "annotationValue": "Year",
                "termSource" : "",
                "termAccession" : "",
                "comments" : []
            }
        },
        {
            "@id": "",
            "comments": [],
            "parameterName": {
                "@id": "",
                "annotationValue": "Location",
                "termSource" : "",
                "termAccession" : "",
                "comments" : []
            }
        },
        {
            "@id": "",
            "comments": [],
            "parameterName": {
                "@id": "",
                "annotationValue": "Repetition",
                "termSource" : "",
                "termAccession" : "",
                "comments" : []
            }
        },
        {
            "@id": "",
            "comments": [],
            "parameterName": {
                "@id": "",
                "annotationValue": "Block",
                "termSource" : "",
                "termAccession" : "",
                "comments" : []
            }
        }
    ],
    "components": [],
    "comments": []
}
